import type { Interaction, Measurement, Protein, Ligand } from '../types';
import { ELEMENT_COLORS, INTERACTION_COLORS } from '../types';
import * as THREE from 'three';

export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

export function downloadCanvas(canvas: HTMLCanvasElement, filename: string): void {
  const link = document.createElement('a');
  link.download = filename;
  link.href = canvas.toDataURL('image/png');
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function interactionsToCSV(interactions: Interaction[]): string {
  const header = 'Type,Donor Residue,Donor Atom,Acceptor Residue,Acceptor Atom,Distance (Å),Angle (°)\n';
  const rows = interactions.map((inter) => {
    const type = inter.type;
    const donorRes = inter.donorResidue ? `${inter.donorResidue.name} ${inter.donorResidue.seqNum}` : 'N/A';
    const donorAtom = inter.donorAtom?.atomName || 'N/A';
    const acceptorRes = inter.acceptorResidue ? `${inter.acceptorResidue.name} ${inter.acceptorResidue.seqNum}` : 'N/A';
    const acceptorAtom = inter.acceptorAtom?.atomName || 'N/A';
    const distance = inter.distance.toFixed(2);
    const angle = inter.angle ? inter.angle.toFixed(1) : 'N/A';
    return `${type},${donorRes},${donorAtom},${acceptorRes},${acceptorAtom},${distance},${angle}`;
  }).join('\n');

  return header + rows;
}

export function generatePyMOLScript(
  protein: Protein | null,
  ligand: Ligand | null,
  interactions: Interaction[],
  measurements: Measurement[],
  camera: THREE.Camera
): string {
  const lines: string[] = [];

  lines.push('# PyMOL Script generated by MolDocking Viewer');
  lines.push('# Generated: ' + new Date().toISOString());
  lines.push('');

  if (protein) {
    lines.push(`# Protein: ${protein.filename}`);
    lines.push(`load ${protein.filename}, protein`);
    lines.push('');
    lines.push('# Protein representation');
    lines.push('hide everything, protein');
    lines.push('show cartoon, protein');
    lines.push('color red, protein and ss h');
    lines.push('color cyan, protein and ss s');
    lines.push('color green, protein and ss l+""');
    lines.push('');
  }

  if (ligand) {
    lines.push(`# Ligand: ${ligand.filename}`);
    lines.push(`load ${ligand.filename}, ligand`);
    lines.push('');
    lines.push('# Ligand representation');
    lines.push('hide everything, ligand');
    lines.push('show sticks, ligand');
    lines.push('show spheres, ligand');
    lines.push('set sphere_scale, 0.25, ligand');
    lines.push('');
    lines.push('# Ligand coloring by element');
    Object.entries(ELEMENT_COLORS).forEach(([element, color]) => {
      const hex = color.replace('#', '0x');
      lines.push(`set_color ${element.toLowerCase()}_color, [${parseInt(hex.substring(2, 4), 16) / 255}, ${parseInt(hex.substring(4, 6), 16) / 255}, ${parseInt(hex.substring(6, 8), 16) / 255}]`);
      lines.push(`color ${element.toLowerCase()}_color, (elem ${element.toLowerCase()} and ligand)`);
    });
    lines.push('');
  }

  if (interactions.length > 0) {
    lines.push('# Interactions');
    const groupedInteractions = interactions.reduce((acc, inter) => {
      if (!acc[inter.type]) acc[inter.type] = [];
      acc[inter.type].push(inter);
      return acc;
    }, {} as Record<string, Interaction[]>);

    Object.entries(groupedInteractions).forEach(([type, list]) => {
      const color = INTERACTION_COLORS[type as keyof typeof INTERACTION_COLORS];
      const hex = color.replace('#', '0x');
      const rgb = [
        parseInt(hex.substring(2, 4), 16) / 255,
        parseInt(hex.substring(4, 6), 16) / 255,
        parseInt(hex.substring(6, 8), 16) / 255,
      ];
      lines.push(`set_color ${type}_color, [${rgb.join(', ')}]`);

      list.forEach((inter, idx) => {
        if (!inter.donorAtom || !inter.acceptorAtom) return;
        const id1 = `/${protein?.name || ''}//${inter.donorAtom.chainId}/${inter.donorAtom.residueId}/${inter.donorAtom.atomName}`;
        const id2 = `/${ligand?.name || ''}//${inter.acceptorAtom.chainId}/${inter.acceptorAtom.residueId}/${inter.acceptorAtom.atomName}`;
        lines.push(`distance ${type}_${idx}, ${id1}, ${id2}`);
        lines.push(`color ${type}_color, ${type}_${idx}`);
        lines.push(`set dash_gap, 0.3, ${type}_${idx}`);
        lines.push(`set dash_length, 0.5, ${type}_${idx}`);
        lines.push(`set dash_width, 1.5, ${type}_${idx}`);
      });
      lines.push('');
    });
  }

  if (measurements.length > 0) {
    lines.push('# Measurements');
    measurements.forEach((meas, idx) => {
      if (meas.type === 'distance' && meas.atoms.length >= 2) {
        const id1 = `//${meas.atoms[0].chainId}/${meas.atoms[0].residueId}/${meas.atoms[0].atomName}`;
        const id2 = `//${meas.atoms[1].chainId}/${meas.atoms[1].residueId}/${meas.atoms[1].atomName}`;
        lines.push(`distance measure_${idx}, ${id1}, ${id2}`);
        lines.push(`label ${id1}, "${meas.atoms[0].atomName}"`);
        lines.push(`label ${id2}, "${meas.atoms[1].atomName}"`);
      }
    });
    lines.push('');
  }

  if (camera) {
    const pos = camera.position;
    const target = new THREE.Vector3(0, 0, 0);
    if (camera instanceof THREE.PerspectiveCamera) {
      const dir = new THREE.Vector3();
      camera.getWorldDirection(dir);
      dir.multiplyScalar(10);
      target.copy(camera.position).add(dir);
    }
    lines.push('# View');
    lines.push(`set_view, (\\`);
    lines.push(`     ${pos.x.toFixed(3)}, ${pos.y.toFixed(3)}, ${pos.z.toFixed(3)}, \\`);
    lines.push(`     ${target.x.toFixed(3)}, ${target.y.toFixed(3)}, ${target.z.toFixed(3)}, \\`);
    lines.push(`     0.000, 1.000, 0.000, \\`);
    lines.push(`     ${(camera instanceof THREE.PerspectiveCamera ? camera.fov * 0.5 : 45).toFixed(2)}, 0.000, 0.000, \\`);
    lines.push(`     -20.000, 20.000, -20.000, \\`);
    lines.push(`     1.000 )`);
    lines.push('');
  }

  lines.push('# Binding pocket surface');
  lines.push('# show surface, protein within 5 of ligand');
  lines.push('# set surface_color, white, protein');
  lines.push('');
  lines.push('zoom');
  lines.push('');

  return lines.join('\n');
}

export function exportPNG(canvas: HTMLCanvasElement, filename: string = 'screenshot.png', _measurements: Measurement[] = []): void {
  downloadCanvas(canvas, filename);
}

export function exportCSV(interactions: Interaction[], filename: string = 'interactions.csv'): void {
  const csv = interactionsToCSV(interactions);
  downloadFile(csv, filename, 'text/csv');
}

export function exportPyMOL(
  protein: Protein | null,
  ligand: Ligand | null,
  interactions: Interaction[],
  measurements: Measurement[],
  camera: any,
  filename: string = 'scene.pml'
): void {
  const script = generatePyMOLScript(protein, ligand, interactions, measurements, camera);
  downloadFile(script, filename, 'text/plain');
}
